export interface TapiocaFoxGLContext {
    gl: WebGL2RenderingContext,
    canvas: HTMLCanvasElement,
    program: WebGLProgram,
    startTime: number,
    lastRenderTime: number,
    devicePixelRatio: number,
    onStart: (start: () => Promise<void>) => void,
    onStop: (stop: () => Promise<void>) => void,
    render: () => void,
    setStatusTitle: (title: string) => void,
    reportStatus: (key: string, status: string) => void,

    // Do not access the things below.
    statusTitle: string,
    statusDict: Record<string, string>,
    vertexShader: string,
    fragmentShader: string,
    javascript: string,
    invokeStart: (() => Promise<void>) | null,
    invokeStop: (() => Promise<void>) | null,
    optimizeViewPort: () => Promise<void>,
    initProgram: (vertexShader: string, fragmentShader: string) => void,
    evalJavaScript: () => void,
    newProgram: () => void,
    reset: () => Promise<void>,
    start: () => void,
    stop: () => void,
    setup: (vertexShader: string, fragmentShader: string, javascript: string) => void,
    run: () => Promise<void>,
}