export interface TapiocaFoxGLContext {
    gl: WebGL2RenderingContext,
    canvas: HTMLCanvasElement,
    program: WebGLProgram,
    startTime: number,
    lastRenderTime: number,
    devicePixelRatio: number,
    statusDict: Record<string, string>,
    vertex_shader: string,
    fragment_shader: string,
    javascript: string,
    animate: (() => void) | null,
    start: (() => void) | null,
    stop: (() => void) | null,
    onStart: (start: () => void) => void,
    onStop: (stop: () => void) => void,
    optimizeViewPort: () => void,
    initProgram: (vertexShader: string, fragmentShader: string) => void,
    newProgram: () => void,
    render: () => void,
    reset: () => void,
    run: (vertex_shader: string, fragment_shader: string, javascript: string) => void,
    reportStatus: (key: string, status: string) => void,
}