# .github/workflows/deploy.yml
name: Deploy Build

on:
  workflow_run:
    workflows: ["Trigger"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build  # change to your build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: upload
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  clean-up:
    runs-on: ubuntu-latest
    # needs: upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          
      - name: Update workflow
        run: |
          ./update_workflow.sh
          
      - name: Clean up branch for Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan clean_branch
          git add -A
          git commit -m "🤖 Clean up. [skip ci]"
          git branch -D main || true
          git branch -m main

      - name: Push build branch
        run: |
          git push origin main --force
          
      - name: Ensure jq is installed
        run: |
          if ! command -v jq &> /dev/null; then
            echo "jq not found, installing..."
            sudo apt-get install -y jq
          else
            echo "jq is already installed"
          fi
          
      - name: Delete all old workflow runs
        run: |
          REPO="${GITHUB_REPOSITORY}"
          TOKEN="${{ secrets.WORKFLOW_PAT }}"
          
          page=1
          while :; do
            runs=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/actions/runs?per_page=100&page=$page" \
              | jq -r ".workflow_runs[] | select(.id != ${GITHUB_RUN_ID}) | .id")

            if [ -z "$runs" ]; then
              break
            fi

            for run_id in $runs; do
              echo "Deleting workflow run $run_id"
              curl -X DELETE -H "Authorization: token $TOKEN" \
                "https://api.github.com/repos/$REPO/actions/runs/$run_id"
            done

            page=$((page + 1))
          done
