# .github/workflows/trigger.yml
name: Trigger

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '43 * * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: echo "Workflow triggered!"
